{{ $namespace := .Release.Name }}
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: {{ print $namespace "-configmap" }}
  envs:
  - ./app.env

generatorOptions:
  disableNameSuffixHash: true